services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5

  watthome:
    build:
      context: ./watthome
    environment:
      FLASK_APP: watthome.py
      FLASK_ENV: development
    ports:
      - "5050:5050"
    depends_on:
      - db
    networks:
      - network

networks:
  network:
    driver: bridge
