CREATE TABLE IF NOT EXISTS kitchen (
    id INT AUTO_INCREMENT PRIMARY KEY,
    date VARCHAR(100),
    value VARCHAR(100)
);
CREATE TABLE IF NOT EXISTS bedroom (
    id INT AUTO_INCREMENT PRIMARY KEY,
    date VARCHAR(100),
    value VARCHAR(100)
);
CREATE TABLE IF NOT EXISTS livingroom (
    id INT AUTO_INCREMENT PRIMARY KEY,
    date VARCHAR(100),
    value VARCHAR(100)
);
CREATE TABLE IF NOT EXISTS bathroom (
    id INT AUTO_INCREMENT PRIMARY KEY,
    date VARCHAR(100),
    value VARCHAR(100)
);
